xfailed clang builds due to compiler error in Elemental:
/usr/bin/clang++-5.0   -I/home/travis/_build/madness/external/source/elemental/include -I/home/travis/_build/madness/external/build/elemental/include -I/home/travis/_install/mpich/include -I/home/travis/_install/madness/include -I/home/travis/_build/madness/external/source/elemental/external/suite_sparse/include  -ftemplate-depth=1024 -Wno-unused-command-line-argument -mno-avx -std=c++14 -std=c++14    -o CMakeFiles/El.dir/src/core/random.cpp.o -c /home/travis/_build/madness/external/source/elemental/src/core/random.cpp
fatal error: error in backend: Unsupported library call operation!
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 5.0.2-svn328729-1~exp1~20180509123505.100 (branches/release_50)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: